name: Build and deploy Monitor API to Azure Web App

env:
  AZURE_WEBAPP_NAME: 'openactivemonitorapi'
  AZURE_WEBAPP_PACKAGE_PATH: 'MonitorApi/published'
  DOTNET_VERSION: '10.x'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build MonitorApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish MonitorApi.csproj --configuration Release --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
